### ISSUE TITLE
NullPointerException on plugin load

### ISSUE THREAD

**Issue by floralpetals** [HuskyDreaming/Settlements#5]
Hello,

after restarting my server, the plugin unfortunately broke with this stacktrace in the logs:
```
java.lang.ExceptionInInitializerError: null
at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42) ~[?:?]
at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185) ~[?:?]
at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132) ~[?:?]
at java.lang.reflect.Field.getFieldAccessor(Field.java:1113) ~[?:?]
at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:886) ~[gson-2.10.1.jar:?]
at com.google.gson.internal.bind.TypeAdapters$29.create(TypeAdapters.java:930) ~[gson-2.10.1.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53) ~[gson-2.10.1.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.1.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[gson-2.10.1.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.1.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.1.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1186) ~[gson-2.10.1.jar:?]
at com.huskydreaming.huskycore.storage.Json.read(Json.java:52) ~[Settlements-0.8.4-ALPHA.jar:?]
at com.huskydreaming.settlements.services.implementations.ConfigServiceImpl.setupLanguage(ConfigServiceImpl.java:43) ~[Settlements-0.8.4-ALPHA.jar:?]
at com.huskydreaming.settlements.services.implementations.LocaleServiceImpl.<init>(LocaleServiceImpl.java:19) ~[Settlements-0.8.4-ALPHA.jar:?]
at com.huskydreaming.settlements.SettlementPlugin.registerServices(SettlementPlugin.java:32) ~[Settlements-0.8.4-ALPHA.jar:?]
at com.huskydreaming.settlements.SettlementPlugin.onEnable(SettlementPlugin.java:20) ~[Settlements-0.8.4-ALPHA.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-450]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-450]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-450]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-450]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-450]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-450]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-450]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-450]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getString(String, String)" because "com.huskydreaming.settlements.storage.types.Message.localeConfiguration" is null
at com.huskydreaming.settlements.storage.types.Message.parse(Message.java:232) ~[Settlements-0.8.4-ALPHA.jar:?]
at com.huskydreaming.settlements.enumeration.Flag.<clinit>(Flag.java:7) ~[Settlements-0.8.4-ALPHA.jar:?]
... 35 more
```
I am running version `0.8.4-ALPHA`.

Thanks in advance!

**Comment by HuskyDreaming** [comment]
Should be fixed now in BETA. Will continue looking into it.
